version: "3.5"

volumes:
  volume1:
  
services:

  gamescore:
    build: .
    ports:
      - "8080:8080"
    links:
      - "mongodb"
      
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - '27017:27017'

      
 
    